<?php
/**
 * IWPEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cielo24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cielo24\Model;
use \Cielo24\ObjectSerializer;

/**
 * IWPEnum Class Doc Comment
 *
 * @category Class
 * @package  Cielo24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IWPEnum
{
    /**
     * Possible values of this enum
     */
    public const PREMIUM = 'PREMIUM';

    public const INTERIM_PROFESSIONAL = 'INTERIM_PROFESSIONAL';

    public const PROFESSIONAL = 'PROFESSIONAL';

    public const SPEAKER_ID = 'SPEAKER_ID';

    public const _FINAL = 'FINAL';

    public const MECHANICAL = 'MECHANICAL';

    public const CUSTOMER_APPROVED_RETURN = 'CUSTOMER_APPROVED_RETURN';

    public const CUSTOMER_APPROVED_TRANSLATION = 'CUSTOMER_APPROVED_TRANSLATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PREMIUM,
            self::INTERIM_PROFESSIONAL,
            self::PROFESSIONAL,
            self::SPEAKER_ID,
            self::_FINAL,
            self::MECHANICAL,
            self::CUSTOMER_APPROVED_RETURN,
            self::CUSTOMER_APPROVED_TRANSLATION
        ];
    }
}


